import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,Play,Timer,Image,History,Save,Download,Upload,Plus,Trash2,RotateCcw,Pause,SkipForward,Shield,AlertTriangle}from'lucide-react';
import'./styles.css';
const POS=['GB','DG','DC','DD','M','MG','MD','A'],FIELD=POS.slice(1),BLOCK=450;
const GROUP={GB:'Gardien',DG:'Défense',DC:'Défense',DD:'Défense',M:'Milieu',MG:'Milieu',MD:'Milieu',A:'Attaque'};
const XY={GB:[50,89],DG:[18,70],DC:[50,73],DD:[82,70],M:[50,50],MG:[20,42],MD:[80,42],A:[50,18]};
const uid=()=>crypto.randomUUID();
const defaults=()=>Array.from({length:12},(_,i)=>({id:uid(),name:i<10?`Joueur ${i+1}`:`Gardien ${i-9}`,keeper:i>9,absent:false,guest:false,startPos:i>9?'GB':'AUTO'}));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const blank=()=>({matches:0,blocks:0,minutes:0,positions:Object.fromEntries(POS.map(x=>[x,0]))});
const choose=(list,score)=>[...list].sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name,'fr'))[0];
function rotation(active,hist){
 if(active.length<8)return{error:'Il faut au moins 8 joueurs disponibles.'};
 if(active.length>12)return{error:'Cette version calcule la rotation pour maximum 12 joueurs présents.'};
 const keep=active.filter(p=>p.keeper);if(keep.length!==2)return{error:'Sélectionnez exactement deux gardiens disponibles.'};
 const dup=FIELD.filter(x=>active.filter(p=>p.startPos===x).length>1);if(dup.length)return{error:`Poste prioritaire attribué deux fois : ${dup.join(', ')}`};
 const[g1,g2]=keep,gk=[g1,g1,g1,g1,g2,g2,g2,g2],slots=64;
 const target=Object.fromEntries(active.map(p=>[p.id,Math.floor(slots/active.length)]));let extra=slots-Object.values(target).reduce((a,b)=>a+b,0);
 const order=[g1,g2,...active.filter(p=>!p.keeper).sort((a,b)=>(hist[a.id]?.blocks||0)-(hist[b.id]?.blocks||0))];
 for(let i=0;i<extra;i++)target[order[i%order.length].id]++;
 target[g1.id]=Math.max(target[g1.id],6);target[g2.id]=Math.max(target[g2.id],6);
 let total=Object.values(target).reduce((a,b)=>a+b,0);while(total>slots){const p=active.filter(x=>!x.keeper&&target[x.id]>4).sort((a,b)=>target[b.id]-target[a.id])[0];if(!p)break;target[p.id]--;total--}
 const used=Object.fromEntries(active.map(p=>[p.id,0])),benchRun=Object.fromEntries(active.map(p=>[p.id,0])),last={},rows=[];
 const fieldKeeper={[g1.id]:[4,6],[g2.id]:[1,3]};
 for(let b=0;b<8;b++){
  const goalie=gk[b],selected=[goalie];used[goalie.id]++;
  const forced=keep.find(k=>k.id!==goalie.id&&fieldKeeper[k.id].includes(b));if(forced){selected.push(forced);used[forced.id]++}
  if(b===0)active.filter(p=>!p.keeper&&p.startPos!=='AUTO').forEach(p=>{if(selected.length<8){selected.push(p);used[p.id]++}});
  while(selected.length<8){const pool=active.filter(p=>p.id!==goalie.id&&!selected.some(x=>x.id===p.id)&&used[p.id]<target[p.id]);const fall=active.filter(p=>p.id!==goalie.id&&!selected.some(x=>x.id===p.id));const p=choose(pool.length?pool:fall,x=>used[x.id]*100-benchRun[x.id]*24+(hist[x.id]?.blocks||0)*.1);selected.push(p);used[p.id]++}
  const assign={GB:goalie},remain=selected.filter(p=>p.id!==goalie.id);
  FIELD.forEach(pos=>{const p=remain.find(x=>x.startPos===pos);if(p){assign[pos]=p;last[p.id]=pos;remain.splice(remain.indexOf(p),1)}});
  FIELD.forEach(pos=>{if(assign[pos])return;const p=choose(remain,x=>{const hp=hist[x.id]?.positions?.[pos]||0;const same=last[x.id]===pos?-100:last[x.id]&&GROUP[last[x.id]]===GROUP[pos]?-35:0;return hp*5+same});assign[pos]=p;last[p.id]=pos;remain.splice(remain.indexOf(p),1)});
  const bench=active.filter(p=>!selected.some(x=>x.id===p.id));active.forEach(p=>benchRun[p.id]=bench.some(x=>x.id===p.id)?benchRun[p.id]+1:0);rows.push({block:b+1,start:b*7.5,end:(b+1)*7.5,assignments:assign,bench});
 }
 return{schedule:rows};
}
const mm=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`,tm=n=>Number.isInteger(n)?`${n}:00`:`${Math.floor(n)}:30`;
function Pitch({row}){return <div className="pitch"><div className="half"/><div className="circle"/>{POS.map(pos=>{const[x,y]=XY[pos],p=row.assignments[pos];return <div className={`token ${GROUP[pos].toLowerCase()}`} style={{left:`${x}%`,top:`${y}%`}} key={pos}><b>{pos}</b><span>{p?.name}</span></div>})}</div>}
function App(){
 const[players,setPlayers]=useState(()=>load('u10-roster',defaults()).map(p=>({...p,startPos:p.startPos||(p.keeper?'GB':'AUTO')})));
 const[history,setHistory]=useState(()=>load('u10-history',{})),[matches,setMatches]=useState(()=>load('u10-matches',[]));
 const[schedule,setSchedule]=useState(()=>load('u10-current',null)),[tab,setTab]=useState('effectif'),[error,setError]=useState(''),[matchName,setMatchName]=useState('Nouveau match');
 const[running,setRunning]=useState(false),[seconds,setSeconds]=useState(BLOCK),[idx,setIdx]=useState(0),endRef=useRef(null),warnRef=useRef(false);
 const active=players.filter(p=>!p.absent),row=schedule?.[idx],next=schedule?.[Math.min(7,idx+1)];
 useEffect(()=>localStorage.setItem('u10-roster',JSON.stringify(players)),[players]);useEffect(()=>localStorage.setItem('u10-history',JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem('u10-matches',JSON.stringify(matches)),[matches]);useEffect(()=>localStorage.setItem('u10-current',JSON.stringify(schedule)),[schedule]);
 const beep=(f=880,d=.25)=>{try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain();o.frequency.value=f;g.gain.value=.16;o.connect(g);g.connect(C.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,C.currentTime+d);o.stop(C.currentTime+d)}catch{}};
 useEffect(()=>{if(!running)return;endRef.current=Date.now()+seconds*1000;const id=setInterval(()=>setSeconds(Math.max(0,Math.ceil((endRef.current-Date.now())/1000))),250);return()=>clearInterval(id)},[running]);
 useEffect(()=>{if(running&&seconds<=60&&!warnRef.current){warnRef.current=true;beep(600,.2);navigator.vibrate?.([200,100,200])}if(running&&seconds===0){setRunning(false);beep(950,.5);setTimeout(()=>beep(1100,.5),550);navigator.vibrate?.([500,150,700])}},[seconds,running]);
 const reset=(n=idx)=>{setRunning(false);setIdx(n);setSeconds(BLOCK);warnRef.current=false};
 const gen=()=>{const r=rotation(active,history);if(r.error){setError(r.error);return}setError('');setSchedule(r.schedule);reset(0);setTab('rotation')};
 const validate=()=>{if(!schedule)return;const h=structuredClone(history);active.forEach(p=>{h[p.id]??=blank();h[p.id].matches++});schedule.forEach(r=>Object.entries(r.assignments).forEach(([pos,p])=>{h[p.id]??=blank();h[p.id].blocks++;h[p.id].minutes+=7.5;h[p.id].positions[pos]=(h[p.id].positions[pos]||0)+1}));setHistory(h);setMatches(m=>[{id:uid(),name:matchName,date:new Date().toLocaleDateString('fr-BE'),schedule},...m]);reset(0);setTab('match')};
 const changes=useMemo(()=>row&&next?active.map(p=>{const a=Object.entries(row.assignments).find(([,x])=>x.id===p.id)?.[0]||'Banc',b=Object.entries(next.assignments).find(([,x])=>x.id===p.id)?.[0]||'Banc';return a!==b?{p,a,b}:null}).filter(Boolean):[],[row,next,active]);
 const backup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,players,history,matches},null,2)],{type:'application/json'}));a.download='rotation-u10-sauvegarde.json';a.click()};
 const restore=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);setPlayers(d.players);setHistory(d.history||{});setMatches(d.matches||[]);alert('Sauvegarde importée.')}catch{alert('Fichier invalide.')}};r.readAsText(f)};
 const add=()=>setPlayers(p=>[...p,{id:uid(),name:`Invité ${p.filter(x=>x.guest).length+1}`,keeper:false,absent:false,guest:true,startPos:'AUTO'}]);
 const downloadPitch=r=>{const node=document.createElement('div');node.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="780"><rect width="1000" height="780" fill="#0f172a"/><rect x="50" y="60" width="900" height="660" rx="12" fill="#16834b" stroke="white" stroke-width="5"/><line x1="50" y1="390" x2="950" y2="390" stroke="white" stroke-width="4"/><circle cx="500" cy="390" r="80" fill="none" stroke="white" stroke-width="4"/>${POS.map(pos=>{const[x,y]=XY[pos],p=r.assignments[pos];return `<circle cx="${x*10}" cy="${60+y*6.6}" r="29" fill="#0f172a" stroke="white" stroke-width="4"/><text x="${x*10}" y="${66+y*6.6}" fill="white" text-anchor="middle" font-size="18" font-weight="bold">${pos}</text><text x="${x*10}" y="${100+y*6.6}" fill="white" text-anchor="middle" font-size="18" font-weight="bold">${p.name}</text>`}).join('')}<text x="50" y="35" fill="white" font-size="25" font-weight="bold">${matchName} • ${tm(r.start)} à ${tm(r.end)}</text><text x="50" y="755" fill="white" font-size="18">Banc : ${r.bench.map(p=>p.name).join(' • ')}</text></svg>`;const blob=new Blob([node.innerHTML],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new window.Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1000;c.height=780;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`rotation-${r.block}.png`;a.click()})};img.src=url};
 const nav=[['effectif',Users,'Effectif'],['rotation',Play,'Rotation'],['match',Timer,'Mode match'],['terrains',Image,'Terrains'],['historique',History,'Historique']];
 return <><header><small>GESTION U10 • 8 CONTRE 8</small><h1>Rotation équitable</h1><p>60 minutes • 8 séquences de 7 min 30</p></header><main><nav>{nav.map(([id,I,l])=><button className={tab===id?'on':''} onClick={()=>setTab(id)}><I size={18}/>{l}</button>)}</nav>
 {tab==='effectif'&&<section className="layout"><div className="card"><h2>Joueurs et poste prioritaire du match</h2>{players.map((p,i)=><div className={`player ${p.absent?'off':''}`} key={p.id}><b>{i+1}</b><input value={p.name} onChange={e=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><select disabled={p.keeper} value={p.keeper?'GB':p.startPos} onChange={e=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,startPos:e.target.value}:x))}><option value="AUTO">Auto</option>{FIELD.map(x=><option>{x}</option>)}</select><button className={p.keeper?'keeper':''} onClick={()=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,keeper:!x.keeper,startPos:!x.keeper?'GB':'AUTO'}:x))}><Shield size={16}/>GB</button><button className={p.absent?'danger':'ok'} onClick={()=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,absent:!x.absent}:x))}>{p.absent?'Absent':'Présent'}</button>{p.guest&&<button onClick={()=>setPlayers(s=>s.filter(x=>x.id!==p.id))}><Trash2 size={16}/></button>}</div>)}</div><aside><div className="card"><button onClick={add}><Plus size={17}/>Ajouter un remplaçant</button></div><div className="card"><h3>Préparer le match</h3><input value={matchName} onChange={e=>setMatchName(e.target.value)}/>{error&&<p className="error"><AlertTriangle size={17}/>{error}</p>}<button className="primary wide" onClick={gen}><RotateCcw size={17}/>Calculer les rotations</button></div><div className="card"><h3>Sauvegarde</h3><button onClick={backup}><Download size={17}/>Exporter</button><label className="button"><Upload size={17}/>Importer<input hidden type="file" accept="application/json" onChange={restore}/></label></div></aside></section>}
 {tab==='rotation'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section><div className="card scroll"><table><thead><tr><th>Temps</th>{POS.map(x=><th>{x}</th>)}<th>Banc</th></tr></thead><tbody>{schedule.map(r=><tr><th>{tm(r.start)} à {tm(r.end)}</th>{POS.map(x=><td>{r.assignments[x].name}</td>)}<td>{r.bench.map(p=>p.name).join(' • ')}</td></tr>)}</tbody></table></div><button className="primary float" onClick={validate}><Save size={17}/>Valider et ouvrir le mode match</button></section>)}
 {tab==='match'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section className="match"><div className="card timer"><small>SÉQUENCE {idx+1} SUR 8</small><div className={seconds<=60?'clock warn':'clock'}>{mm(seconds)}</div><p>{tm(row.start)} à {tm(row.end)}</p><div className="controls"><button className="primary" onClick={()=>{beep(440,.08);setRunning(x=>!x)}}>{running?<><Pause/>Pause</>:<><Play/>Démarrer</>}</button><button onClick={()=>reset()}><RotateCcw/></button><button disabled={idx===7} onClick={()=>reset(Math.min(7,idx+1))}><SkipForward/></button></div><Pitch row={row}/><p><b>Banc actuel :</b> {row.bench.map(p=>p.name).join(' • ')}</p></div><div className="card"><h2>Prochains changements</h2>{idx===7?<p>Dernière séquence.</p>:changes.map(c=><div className="change"><b>{c.p.name}</b><span>{c.a} → {c.b}</span></div>)}{idx<7&&<p className="next"><b>Prochain banc :</b> {next.bench.map(p=>p.name).join(' • ')}</p>}</div></section>)}
 {tab==='terrains'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section className="grounds">{schedule.map(r=><div className="card"><div className="row"><h3>Séquence {r.block} • {tm(r.start)} à {tm(r.end)}</h3><button onClick={()=>downloadPitch(r)}><Download size={16}/>PNG</button></div><Pitch row={r}/><p><b>Banc :</b> {r.bench.map(p=>p.name).join(' • ')}</p></div>)}</section>)}
 {tab==='historique'&&<section className="layout"><div className="card scroll"><h2>Historique des positions</h2><table><thead><tr><th>Joueur</th><th>Minutes</th>{POS.map(x=><th>{x}</th>)}</tr></thead><tbody>{players.filter(p=>!p.guest).map(p=>{const s=history[p.id]||blank();return <tr><th>{p.name}</th><td>{s.minutes}</td>{POS.map(x=><td>{s.positions[x]||0}</td>)}</tr>})}</tbody></table></div><aside className="card"><h2>Matchs enregistrés</h2>{matches.map(m=><p>✓ <b>{m.name}</b><br/><small>{m.date}</small></p>)}</aside></section>)}
 </main></>}
function Empty({go}){return <div className="card empty"><Play size={45}/><h2>Aucune rotation active</h2><button onClick={go}>Préparer le match</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
