import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Users,Play,Timer,History,Save,Plus,Trash2,RotateCcw,Pause,SkipForward,Shield,AlertTriangle,Download,Upload}from'lucide-react';
import'./styles.css';
const POS=['GB','DG','DC','DD','M','MG','MD','A'],FIELD=POS.slice(1),XY={GB:[50,89],DG:[18,70],DC:[50,73],DD:[82,70],M:[50,50],MG:[20,42],MD:[80,42],A:[50,18]},BLOCK=450;
const uid=()=>crypto.randomUUID(),blank=()=>({matches:0,minutes:0,positions:Object.fromEntries(POS.map(x=>[x,0]))});
const defaults=()=>Array.from({length:12},(_,i)=>({id:uid(),name:i<10?`Joueur ${i+1}`:`Gardien ${i-9}`,keeper:i>9,absent:false,guest:false,startPos:i>9?'GB':'AUTO'}));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},pick=(a,f)=>[...a].sort((x,y)=>f(x)-f(y)||x.name.localeCompare(y.name,'fr'))[0];
function makeRotation(active,hist){
 if(active.length<8)return{error:'Il faut au moins 8 joueurs disponibles.'};if(active.length>12)return{error:'Maximum 12 joueurs présents.'};
 const keep=active.filter(p=>p.keeper);if(keep.length!==2)return{error:'Sélectionnez exactement deux gardiens.'};
 const dup=FIELD.filter(pos=>active.filter(p=>p.startPos===pos).length>1);if(dup.length)return{error:`Poste attribué deux fois : ${dup.join(', ')}`};
 const[g1,g2]=keep,gks=[g1,g1,g1,g1,g2,g2,g2,g2],used=Object.fromEntries(active.map(p=>[p.id,0])),last={},rows=[];
 const target=Object.fromEntries(active.map(p=>[p.id,5]));target[g1.id]=6;target[g2.id]=6;active.filter(p=>!p.keeper).sort((a,b)=>(hist[a.id]?.minutes||0)-(hist[b.id]?.minutes||0)).slice(0,2).forEach(p=>target[p.id]=6);
 const keeperField={[g1.id]:[4,6],[g2.id]:[1,3]};
 for(let b=0;b<8;b++){
  const gk=gks[b],selected=[gk];used[gk.id]++;
  const other=keep.find(k=>k.id!==gk.id&&keeperField[k.id].includes(b));if(other){selected.push(other);used[other.id]++}
  if(b===0)active.filter(p=>!p.keeper&&p.startPos!=='AUTO').forEach(p=>{if(selected.length<8){selected.push(p);used[p.id]++}});
  while(selected.length<8){const available=active.filter(p=>p.id!==gk.id&&!selected.some(x=>x.id===p.id)),pool=available.filter(p=>used[p.id]<target[p.id]),p=pick(pool.length?pool:available,x=>used[x.id]*100+(hist[x.id]?.minutes||0));selected.push(p);used[p.id]++}
  const assignments={GB:gk},remain=selected.filter(p=>p.id!==gk.id);
  FIELD.forEach(pos=>{const p=remain.find(x=>x.startPos===pos);if(p){assignments[pos]=p;last[p.id]=pos;remain.splice(remain.indexOf(p),1)}});
  FIELD.forEach(pos=>{if(assignments[pos])return;const p=pick(remain,x=>(last[x.id]===pos?-100:0)+(hist[x.id]?.positions?.[pos]||0)*5);assignments[pos]=p;last[p.id]=pos;remain.splice(remain.indexOf(p),1)});
  rows.push({block:b+1,start:b*7.5,end:(b+1)*7.5,assignments,bench:active.filter(p=>!selected.some(x=>x.id===p.id))});
 }
 return{schedule:rows};
}
const clock=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`,mt=n=>Number.isInteger(n)?`${n}:00`:`${Math.floor(n)}:30`;
function Pitch({row}){return <div className="pitch"><div className="half"/><div className="circle"/>{POS.map(pos=>{const[x,y]=XY[pos];return <div className="token" style={{left:`${x}%`,top:`${y}%`}} key={pos}><b>{pos}</b><span>{row.assignments[pos]?.name}</span></div>})}</div>}
function Empty({go}){return <div className="card empty"><Play size={42}/><h2>Aucune rotation active</h2><button onClick={go}>Préparer le match</button></div>}
function App(){
 const[players,setPlayers]=useState(()=>load('u10-roster',defaults())),[history,setHistory]=useState(()=>load('u10-history',{})),[matches,setMatches]=useState(()=>load('u10-matches',[])),[schedule,setSchedule]=useState(()=>load('u10-current',null));
 const[tab,setTab]=useState('effectif'),[error,setError]=useState(''),[name,setName]=useState('Nouveau match'),[running,setRunning]=useState(false),[seconds,setSeconds]=useState(BLOCK),[idx,setIdx]=useState(0),end=useRef(0),warn=useRef(false);
 const active=players.filter(p=>!p.absent),row=schedule?.[idx],next=schedule?.[Math.min(7,idx+1)];
 useEffect(()=>localStorage.setItem('u10-roster',JSON.stringify(players)),[players]);useEffect(()=>localStorage.setItem('u10-history',JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem('u10-matches',JSON.stringify(matches)),[matches]);useEffect(()=>localStorage.setItem('u10-current',JSON.stringify(schedule)),[schedule]);
 const beep=(f=800,d=.2)=>{try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain();o.frequency.value=f;g.gain.value=.15;o.connect(g);g.connect(C.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,C.currentTime+d);o.stop(C.currentTime+d)}catch{}};
 useEffect(()=>{if(!running)return;end.current=Date.now()+seconds*1000;const id=setInterval(()=>setSeconds(Math.max(0,Math.ceil((end.current-Date.now())/1000))),250);return()=>clearInterval(id)},[running]);
 useEffect(()=>{if(running&&seconds<=60&&!warn.current){warn.current=true;beep();navigator.vibrate?.([200,100,200])}if(running&&seconds===0){setRunning(false);beep(1000,.5);navigator.vibrate?.([500,150,700])}},[seconds,running]);
 const reset=(n=idx)=>{setRunning(false);setIdx(n);setSeconds(BLOCK);warn.current=false};
 const generate=()=>{const r=makeRotation(active,history);if(r.error){setError(r.error);return}setError('');setSchedule(r.schedule);reset(0);setTab('rotation')};
 const validate=()=>{const h=structuredClone(history);active.forEach(p=>{h[p.id]??=blank();h[p.id].matches++});schedule.forEach(r=>Object.entries(r.assignments).forEach(([pos,p])=>{h[p.id]??=blank();h[p.id].minutes+=7.5;h[p.id].positions[pos]=(h[p.id].positions[pos]||0)+1}));setHistory(h);setMatches(m=>[{id:uid(),name,date:new Date().toLocaleDateString('fr-BE')},...m]);reset(0);setTab('match')};
 const changes=useMemo(()=>row&&next?active.map(p=>{const a=Object.entries(row.assignments).find(([,x])=>x.id===p.id)?.[0]||'Banc',b=Object.entries(next.assignments).find(([,x])=>x.id===p.id)?.[0]||'Banc';return a!==b?{p,a,b}:null}).filter(Boolean):[],[row,next,active]);
 const backup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({players,history,matches},null,2)],{type:'application/json'}));a.download='rotation-u10.json';a.click()};
 const restore=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);setPlayers(d.players);setHistory(d.history||{});setMatches(d.matches||[]);alert('Sauvegarde importée')}catch{alert('Fichier invalide')}};r.readAsText(f)};
 const nav=[['effectif',Users,'Effectif'],['rotation',Play,'Rotation'],['match',Timer,'Mode match'],['terrains',Download,'Terrains'],['historique',History,'Historique']];
 return <><header><small>GESTION U10 • 8 CONTRE 8</small><h1>Rotation équitable</h1><p>60 minutes • 8 séquences de 7 min 30</p></header><main><nav>{nav.map(([id,I,label])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><I size={17}/>{label}</button>)}</nav>
 {tab==='effectif'&&<section className="layout"><div className="card"><h2>Joueurs et poste prioritaire</h2>{players.map((p,i)=><div className={`player ${p.absent?'off':''}`} key={p.id}><b>{i+1}</b><input value={p.name} onChange={e=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><select disabled={p.keeper} value={p.keeper?'GB':p.startPos} onChange={e=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,startPos:e.target.value}:x))}><option value="AUTO">Auto</option>{FIELD.map(x=><option key={x}>{x}</option>)}</select><button className={p.keeper?'keeper':''} onClick={()=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,keeper:!x.keeper,startPos:!x.keeper?'GB':'AUTO'}:x))}><Shield size={15}/>GB</button><button onClick={()=>setPlayers(s=>s.map(x=>x.id===p.id?{...x,absent:!x.absent}:x))}>{p.absent?'Absent':'Présent'}</button>{p.guest&&<button onClick={()=>setPlayers(s=>s.filter(x=>x.id!==p.id))}><Trash2 size={15}/></button>}</div>)}</div><aside><div className="card"><button onClick={()=>setPlayers(s=>[...s,{id:uid(),name:'Invité',keeper:false,absent:false,guest:true,startPos:'AUTO'}])}><Plus size={16}/>Ajouter un remplaçant</button></div><div className="card"><h3>Préparer le match</h3><input value={name} onChange={e=>setName(e.target.value)}/>{error&&<p className="error"><AlertTriangle size={16}/>{error}</p>}<button className="primary wide" onClick={generate}><RotateCcw size={16}/>Calculer</button></div><div className="card"><button onClick={backup}><Download size={16}/>Exporter</button><label className="button"><Upload size={16}/>Importer<input hidden type="file" onChange={restore}/></label></div></aside></section>}
 {tab==='rotation'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section><div className="card scroll"><table><thead><tr><th>Temps</th>{POS.map(x=><th key={x}>{x}</th>)}<th>Banc</th></tr></thead><tbody>{schedule.map(r=><tr key={r.block}><th>{mt(r.start)} à {mt(r.end)}</th>{POS.map(x=><td key={x}>{r.assignments[x].name}</td>)}<td>{r.bench.map(p=>p.name).join(' • ')}</td></tr>)}</tbody></table></div><button className="primary float" onClick={validate}><Save size={16}/>Valider et ouvrir le mode match</button></section>)}
 {tab==='match'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section className="match"><div className="card timer"><small>SÉQUENCE {idx+1} SUR 8</small><div className={seconds<=60?'clock warn':'clock'}>{clock(seconds)}</div><p>{mt(row.start)} à {mt(row.end)}</p><div className="controls"><button className="primary" onClick={()=>{beep(440,.08);setRunning(x=>!x)}}>{running?<><Pause/>Pause</>:<><Play/>Démarrer</>}</button><button onClick={()=>reset()}><RotateCcw/></button><button disabled={idx===7} onClick={()=>reset(Math.min(7,idx+1))}><SkipForward/></button></div><Pitch row={row}/><p><b>Banc actuel :</b> {row.bench.map(p=>p.name).join(' • ')}</p></div><div className="card"><h2>Prochains changements</h2>{idx===7?<p>Dernière séquence.</p>:changes.map(c=><div className="change" key={c.p.id}><b>{c.p.name}</b><span>{c.a} → {c.b}</span></div>)}{idx<7&&<p className="next"><b>Prochain banc :</b> {next.bench.map(p=>p.name).join(' • ')}</p>}</div></section>)}
 {tab==='terrains'&&(!schedule?<Empty go={()=>setTab('effectif')}/>:<section className="grounds">{schedule.map(r=><div className="card" key={r.block}><h3>Séquence {r.block} • {mt(r.start)} à {mt(r.end)}</h3><Pitch row={r}/><p><b>Banc :</b> {r.bench.map(p=>p.name).join(' • ')}</p></div>)}</section>)}
 {tab==='historique'&&<section className="layout"><div className="card scroll"><h2>Historique</h2><table><thead><tr><th>Joueur</th><th>Minutes</th>{POS.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{players.filter(p=>!p.guest).map(p=>{const s=history[p.id]||blank();return <tr key={p.id}><th>{p.name}</th><td>{s.minutes}</td>{POS.map(x=><td key={x}>{s.positions[x]||0}</td>)}</tr>})}</tbody></table></div><aside className="card"><h2>Matchs enregistrés</h2>{matches.map(m=><p key={m.id}>✓ <b>{m.name}</b><br/><small>{m.date}</small></p>)}</aside></section>)}
 </main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
